apiVersion: v1
kind: Service
metadata:
  name: ai-service
  namespace: dev
spec:
  selector:
    app: ai-service
  ports:
    - port: 3002
      targetPort: 3002
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-service
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-service
  template:
    metadata:
      labels:
        app: ai-service
    spec:
      containers:
        - name: ai-service
          image: gcr.io/project-30677b2a-4acb-4641-a9f/ai-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3002
          envFrom:
            - configMapRef:
                name: db-and-kafka-config
            - secretRef:
                name: ai-summrizer-secret
      resources:
        requests:
          cpu: "100m"
          memory: "100Mi"
        limits:
          cpu: "200m"
          memory: "200Mi"
