apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myapp-ingress
  namespace: dev
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: warmup.cloud
      http:
        paths:
          - path: /summarizer(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: summarizer-service
                port:
                  number: 3000
