apiVersion: v1
kind: Service
metadata:
  name: summarizer-service
spec:
  selector:
    app: summarizer-service
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: summarizer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: summarizer-service
  template:
    metadata:
      labels:
        app: summarizer-service
    spec:
      containers:
        - name: summarizer-service
          image: summarizer-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: db-and-kafka-config
            - secretRef:
                name: ai-summrizer-secret
